@startuml Robodogドメインモデル図
skinparam componentStyle rectangle
' 事務職員向けの情報システム
[システム] o-- [ユーザー(職員)]
[システム] o-- [ユーザー(学生)]

[ユーザー(学生)] o-- [学生証]
[ユーザー(職員)] o-- [職員証]

[学生証] o-- [学生番号]
[学生証] o-- [生年月日]
[学生証] o-- [氏名]
[学生証] o-- [メールアドレス]

[職員証] o-- [職員番号]
[職員証] o-- [生年月日]
[職員証] o-- [氏名]
[職員証] o-- [メールアドレス]

[本] o-- [書籍]
[本] o-- [雑誌]
[書籍] o-- [管理番号]