@startuml 
left to right direction

actor ユーザー

rectangle "Web訪問者システム" {
  ユーザー -- (新規登録できる)
  ユーザー -- (ログインできる)
  ユーザー -- (自分と他の訪問者情報を参照できる)
  ユーザー -- (自分の登録情報を変更できる)
  ユーザー -- (自分の登録情報を削除できる)
  ユーザー -- (ログアウトできる)
}

@enduml