@startuml 図書館システム
skinparam componentStyle rectangle

' 図書館
[図書館システム] o-- [利用者]


[利用者] o-- [ユーザー(学生)]
[利用者] o-- [ユーザー(職員)]


[ユーザー(学生)] o-- [学生証]
[ユーザー(職員)] o-- [職員証]

[学生証] o-- [学生番号]
[学生証] o-- [氏名]
[学生証] o-- [メールアドレス]
[学生証] o-- [生年月日]


[職員証] o-- [職員番号]
[職員証] o-- [番号]
[職員証] o-- [氏名]
[職員証] o-- [メールアドレス]

[本] o-- [書籍]
[本] o-- [雑誌]


@enduml