@startuml 注文管理システム
skinparam componentStyle rectangle

[ユーザー] o-- [ユーザーID]
[ユーザー] o-- [名前]
[ユーザー] o-- [電話番号]
[ユーザー] o-- [メールアドレス]
[ユーザー] o-- [住所]
[ユーザー] o-- [クレジットカード]
[ユーザー] o-- [支払情報]
[ユーザー] o-- [カート]

[クレジットカード] o-- [カード番号]
[クレジットカード] o-- [セキュリティコード]

'[カート] o-- [ユーザーID]
[カート] o-- [商品]
[カート] o-- [商品ID]
[カート] o-- [商品の数量]
[カート] o-- [商品の小計]
[カート] o-- [注文ID]

[支払情報] o-- [支払ID]
[支払情報] o-- [支払日時]
[支払情報] o-- [支払金額]



[管理者] o-- [名前]
[管理者] o-- [管理者ID]
[管理者] o-- [決済履歴]
[管理者] o-- [注文履歴]

[決済履歴] o-- [決済ID]
[決済履歴] o-- [注文ID]
[決済履歴] o-- [顧客ID]
[決済履歴] o-- [決済金額]
[決済履歴] o-- [決済日時]



[商品] o-- [商品名]
[商品] o-- [商品ID]
[商品] o-- [商品の詳細]
[商品] o-- [値段]
[商品] o-- [在庫数]

[注文] o-- [注文ID]
[注文] o-- [ユーザーID]
[注文] o-- [注文日時]
[注文] o-- [合計金額]

[注文履歴] o-- [商品ID]
[注文履歴] o-- [注文ID]
[注文履歴] o-- [注文日時]
[注文履歴] o-- [決済金額]

[返品] o-- [返品ID]
[返品] o-- [商品ID]
[返品] o-- [商品名]
[返品] o-- [返品理由]
[返品] o-- [商品の状態]
[返品] o-- [返品日時]
[返品] o-- [返金]

[返金] o-- [返金ID]
[返金] o-- [返金日時]
[返金] o-- [返金金額]

@enduml