@startuml 図書館システム
skinparam componentStyle rectangle

' 図書館
[会員] o-- [会員番号]
[会員] o-- [氏名]
[会員] o-- [メールアドレス]

[会員番号] <|-- [学生番号]
[会員番号] <|-- [職員番号]

[職員] o-- [職員番号]
[学生] o-- [学生番号]
[会員] <|-- [学生]
[会員] <|-- [職員]

[予約の情報] o-- [予約情報]
[予約情報] o-- [予約日時]
[予約の情報] o-- [図書]

[図書] <|-- [書籍]
[図書] <|-- [雑誌]
[図書] o-- [管理番号]
[図書] o-- [書名]
[図書] o-- [著者]
[図書] o-- [出版社]
[図書] o-- [ISBN]

[貸出情報] o-- [会員]
[貸出情報] o-- [図書]
[貸出情報] o-- [貸出日]
[貸出情報] o-- [返却日]

@enduml